# Generated by Django 5.2.1 on 2025-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('normalized_question', models.TextField(editable=False, unique=True, verbose_name='Нормализованный вопрос')),
                ('answer', models.TextField(verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
    ]
