# Generated by Django 5.2.1 on 2025-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='normalized_question',
            field=models.TextField(unique=True, verbose_name='Нормализованный вопрос'),
        ),
    ]
